# Generated by Django 3.2.7 on 2021-09-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='Department',
        ),
        migrations.AddField(
            model_name='teachers',
            name='Department',
            field=models.ManyToManyField(to='Management.Departments'),
        ),
    ]
