# Generated by Django 3.2.7 on 2021-09-12 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_auto_20210912_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='Department',
        ),
        migrations.AddField(
            model_name='teachers',
            name='Department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Management.departments'),
        ),
    ]
