# Generated by Django 3.2.7 on 2021-09-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_auto_20210912_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='Department',
        ),
        migrations.AddField(
            model_name='teachers',
            name='Department',
            field=models.ManyToManyField(to='Management.Departments'),
        ),
    ]
