# Generated by Django 3.2.7 on 2021-09-12 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_auto_20210912_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.departments'),
        ),
        migrations.AlterField(
            model_name='students',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='Subject',
            field=models.CharField(max_length=50),
        ),
    ]
