# Generated by Django 3.2.7 on 2021-09-12 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_auto_20210912_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='Department',
            new_name='DeptStudent',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='Department',
            new_name='DeptTeacher',
        ),
    ]
